### ISSUE TITLE
Simply NPC AI example appears to be broken

### ISSUE THREAD

**Issue by 0awful** [Sollimann/bonsai#28]
# Behavior
An error is thrown on cargo build:
```
error[E0446]: crate-private type `SequenceArgs<'_, A, E, F, B>` in public interface
  --> /home/guest/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bonsai-bt-0.6.0/src/sequence.rs:19:1
   |
4  |   pub(crate) struct SequenceArgs<'a, A, E, F, B> {
   |   ---------------------------------------------- `SequenceArgs<'_, A, E, F, B>` declared as crate-private
...
19 | / pub fn sequence<A, E, F, B>(args: SequenceArgs<A, E, F, B>) -> (Status, f64)
20 | | where
21 | |     A: Clone,
22 | |     E: UpdateEvent,
23 | |     F: FnMut(ActionArgs<E, A>, &mut B) -> (Status, f64),
24 | |     A: Debug,
   | |_____________^ can't leak crate-private type

For more information about this error, try `rustc --explain E0446`.
error: could not compile `bonsai-bt` (lib) due to previous error
```

# Steps to Replicate
Copy enemy npc code into a project. Run cargo build

**Comment by kembofly** [comment]
@0awful will have a look at it today or tomorrow! Looks like we just need to make SequenceArgs `pub` instead of `pub(crate)`

**Comment by 0awful** [comment]
Sounds good. I'll gladly check it works when you've got it going

**Comment by Sollimann** [comment]
@0awful I don't seem to be able to reproduce your problem which is a bit strange. Everything seems to work as intended for me.

here is my test setup.

Cargo.toml
```toml
[package]
name = "bonsai-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bonsai-bt = { git = "https://github.com/Sollimann/bonsai", branch = "main" }
bonsai-bt = "0.6.0"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
```
I copy-pasted the [simple ai main.rs](https://github.com/Sollimann/bonsai/blob/main/examples/src/simple_npc_ai/main.rs) file, and when running `cargo run` I get:

```sh
❯ cargo build
    Blocking waiting for file lock on package cache
   Compiling bonsai-bt v0.6.0
   Compiling bonsai-test v0.1.0 (/Users/sollimann/Documents/coding/bonsai-test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/bonsai-test`
reached main loop...
NPC is alive...
NPC has action points: 3
Performing action: run. Action points: 2
Performing action: shoot. Action points: 1
NPC has action points: 1
Performing action: run. Action points: 0
Cannot perform action: shoot. Not enough action points.
NPC does not have actions points left...
Rested for a while... Action points: 1
reached main loop...
Rested for a while... Action points: 2
reached main loop...
Rested for a while... Action points: 3
reached main loop...
NPC died...
NPC is dead...
NPC shot 2 times during the simulation.
```

Which version of Rust are you running? I just tested with 1.74.0 (stable)

Also, can you do `cargo clean` and then try again?
